### ISSUE TITLE
Repository for EPEL7?

### ISSUE THREAD

**Issue by mcepl** [MSchuwalow/spec-zotero#1]
Please? I think serious types (e.g., people who use Linux for their work, not for developing other software, which is a case for most Zotero users) could have tendency to use RHEL/CentOS. I know that whole my family (including my wife who is PhD student) does.

And eventually we can find out how to build truly from sources (I guess inspiration from https://packages.debian.org/sid/zotero-standalone could be useful).

**Comment by MSchuwalow** [comment]
Hi. This is mostly for my own use -- even though I do have it on copr. 
https://copr.fedorainfracloud.org/coprs/mschuwalow/zotero/

I don't intend to put this on epel in the foreseeable future. But the specfile is reasonably simple and should work on rhel/centos without modifications. I can offer to see if it builds and installs correctly on centos and then add those versions to copr.

**Comment by mcepl** [comment]
It does build and works here.

**Comment by MSchuwalow** [comment]
Alright. I added EPEL6/7 on copr. You should be able to install it from there.

Closing the issue.
